" Plugins
" --------------
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-surround'
Plugin 'preservim/nerdtree'
Plugin 'tpope/vim-ragtag'
call vundle#end()

" ------
" General
" ------
colorscheme peachpuff
syntax on					" syntax highlighting
filetype plugin indent on	" use file type plugin


" ------
" General set
" ------
set number			" show linenumbers
set relativenumber	" show relative linenumbers
set shiftwidth=4	" number of spaces to use on autoindenting
set tabstop=4		" tab is 4 spaces
set shiftround		" use multiple of shiftwidth when indenting with < and > 
set autoindent		" always set autoindenting on

" ------
" Keymaps
" ------
nnoremap ; :
nnoremap : ;

nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-H> <C-W><C-H>

" https://github.com/preservim/nerdtree
nnoremap <C-t> :NERDTreeToggle<CR>

"""
"Other"
"""
" Skeletons
augroup skeletons
	au!
	autocmd BufNewFile *.* silent! execute '0r ~/.vim/templates/skeleton.'.expand("<afile>:e")
augroup END
